language: python
python:
    - "2.7"
    - "3.3"

install:
  - pip install . --use-mirrors
  - pip install -r dev_requirements.txt
  - pip install python-coveralls

branches:
  only:
    - master
    - test

script:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then coverage run `which py.test`; fi
  - doit
  - py.test

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then coveralls; fi


notifications:
    email:
        on_success: change
        on_failure: change
